// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sitemgrsvc.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sitemgrsvc.proto

It has these top-level messages:
	CreateNewSiteRequest
	CreateNewSiteReply
	ProxyDeleteSiteRequest
	ProxyDeleteSiteReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The new site request contains two parameters.
type CreateNewSiteRequest struct {
	UserId   uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Sitename string `protobuf:"bytes,2,opt,name=sitename" json:"sitename,omitempty"`
}

func (m *CreateNewSiteRequest) Reset()                    { *m = CreateNewSiteRequest{} }
func (m *CreateNewSiteRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNewSiteRequest) ProtoMessage()               {}
func (*CreateNewSiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateNewSiteRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateNewSiteRequest) GetSitename() string {
	if m != nil {
		return m.Sitename
	}
	return ""
}

// The new site response contains the result of the creation.
type CreateNewSiteReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *CreateNewSiteReply) Reset()                    { *m = CreateNewSiteReply{} }
func (m *CreateNewSiteReply) String() string            { return proto.CompactTextString(m) }
func (*CreateNewSiteReply) ProtoMessage()               {}
func (*CreateNewSiteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateNewSiteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ProxyDeleteSiteRequest struct {
	SiteId uint64 `protobuf:"varint,1,opt,name=site_id,json=siteId" json:"site_id,omitempty"`
}

func (m *ProxyDeleteSiteRequest) Reset()                    { *m = ProxyDeleteSiteRequest{} }
func (m *ProxyDeleteSiteRequest) String() string            { return proto.CompactTextString(m) }
func (*ProxyDeleteSiteRequest) ProtoMessage()               {}
func (*ProxyDeleteSiteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProxyDeleteSiteRequest) GetSiteId() uint64 {
	if m != nil {
		return m.SiteId
	}
	return 0
}

// The new site response contains the result of the creation.
type ProxyDeleteSiteReply struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *ProxyDeleteSiteReply) Reset()                    { *m = ProxyDeleteSiteReply{} }
func (m *ProxyDeleteSiteReply) String() string            { return proto.CompactTextString(m) }
func (*ProxyDeleteSiteReply) ProtoMessage()               {}
func (*ProxyDeleteSiteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProxyDeleteSiteReply) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateNewSiteRequest)(nil), "pb.CreateNewSiteRequest")
	proto.RegisterType((*CreateNewSiteReply)(nil), "pb.CreateNewSiteReply")
	proto.RegisterType((*ProxyDeleteSiteRequest)(nil), "pb.ProxyDeleteSiteRequest")
	proto.RegisterType((*ProxyDeleteSiteReply)(nil), "pb.ProxyDeleteSiteReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sitemgr service

type SitemgrClient interface {
	// Create a new site.
	NewSite(ctx context.Context, in *CreateNewSiteRequest, opts ...grpc.CallOption) (*CreateNewSiteReply, error)
	DeleteSite(ctx context.Context, in *ProxyDeleteSiteRequest, opts ...grpc.CallOption) (*ProxyDeleteSiteReply, error)
}

type sitemgrClient struct {
	cc *grpc.ClientConn
}

func NewSitemgrClient(cc *grpc.ClientConn) SitemgrClient {
	return &sitemgrClient{cc}
}

func (c *sitemgrClient) NewSite(ctx context.Context, in *CreateNewSiteRequest, opts ...grpc.CallOption) (*CreateNewSiteReply, error) {
	out := new(CreateNewSiteReply)
	err := grpc.Invoke(ctx, "/pb.Sitemgr/NewSite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sitemgrClient) DeleteSite(ctx context.Context, in *ProxyDeleteSiteRequest, opts ...grpc.CallOption) (*ProxyDeleteSiteReply, error) {
	out := new(ProxyDeleteSiteReply)
	err := grpc.Invoke(ctx, "/pb.Sitemgr/DeleteSite", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sitemgr service

type SitemgrServer interface {
	// Create a new site.
	NewSite(context.Context, *CreateNewSiteRequest) (*CreateNewSiteReply, error)
	DeleteSite(context.Context, *ProxyDeleteSiteRequest) (*ProxyDeleteSiteReply, error)
}

func RegisterSitemgrServer(s *grpc.Server, srv SitemgrServer) {
	s.RegisterService(&_Sitemgr_serviceDesc, srv)
}

func _Sitemgr_NewSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SitemgrServer).NewSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sitemgr/NewSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SitemgrServer).NewSite(ctx, req.(*CreateNewSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sitemgr_DeleteSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyDeleteSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SitemgrServer).DeleteSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sitemgr/DeleteSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SitemgrServer).DeleteSite(ctx, req.(*ProxyDeleteSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sitemgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sitemgr",
	HandlerType: (*SitemgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSite",
			Handler:    _Sitemgr_NewSite_Handler,
		},
		{
			MethodName: "DeleteSite",
			Handler:    _Sitemgr_DeleteSite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sitemgrsvc.proto",
}

func init() { proto.RegisterFile("sitemgrsvc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc5, 0x30,
	0x14, 0x44, 0xcd, 0x53, 0x5e, 0x7d, 0x77, 0x55, 0x2e, 0xa5, 0x86, 0xac, 0x4a, 0x16, 0xd2, 0x55,
	0x41, 0x5d, 0xbb, 0xb2, 0x9b, 0x22, 0x88, 0xa4, 0x1f, 0x20, 0xad, 0xbd, 0x48, 0xa1, 0xb5, 0x31,
	0x49, 0xd5, 0xfe, 0x84, 0xdf, 0x2c, 0xa9, 0xa2, 0x52, 0xb3, 0xcb, 0x30, 0xc9, 0x99, 0x99, 0x40,
	0x6c, 0x7b, 0x47, 0xe3, 0x93, 0xb1, 0xaf, 0x8f, 0x85, 0x36, 0x93, 0x9b, 0x70, 0xa7, 0x5b, 0x79,
	0x0b, 0xc9, 0x8d, 0xa1, 0xc6, 0xd1, 0x1d, 0xbd, 0xd5, 0xbd, 0x23, 0x45, 0x2f, 0x33, 0x59, 0x87,
	0x67, 0x10, 0xcd, 0x96, 0xcc, 0x43, 0xdf, 0x71, 0x96, 0xb1, 0xfc, 0x44, 0xed, 0xbd, 0xac, 0x3a,
	0x14, 0x70, 0xea, 0x41, 0xcf, 0xcd, 0x48, 0x7c, 0x97, 0xb1, 0xfc, 0xa0, 0x7e, 0xb4, 0x3c, 0x07,
	0xdc, 0xc0, 0xf4, 0xb0, 0x60, 0x0c, 0xc7, 0x64, 0xcc, 0x8a, 0x39, 0x28, 0x7f, 0x94, 0x17, 0x90,
	0xde, 0x9b, 0xe9, 0x7d, 0x29, 0x69, 0x20, 0x47, 0x9b, 0x58, 0x4f, 0xfb, 0x13, 0xeb, 0x65, 0xd5,
	0xc9, 0x1c, 0x92, 0x7f, 0x4f, 0x82, 0xf0, 0xcb, 0x0f, 0x06, 0x51, 0xfd, 0x35, 0x15, 0xaf, 0x21,
	0xfa, 0xae, 0x82, 0xbc, 0xd0, 0x6d, 0x11, 0x9a, 0x2a, 0xd2, 0x80, 0xa3, 0x87, 0x45, 0x1e, 0x61,
	0x09, 0xf0, 0x9b, 0x87, 0xc2, 0xdf, 0x0b, 0xf7, 0x16, 0x3c, 0xe8, 0xad, 0x94, 0x76, 0xbf, 0xfe,
	0xf6, 0xd5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x11, 0x08, 0x8d, 0x81, 0x01, 0x00, 0x00,
}
